### ISSUE TITLE
Document checklist for new cohort: Application platform and documents

### ISSUE THREAD

**Issue by malvikasharan** [open-life-science/application-forms#7]
**Website**
- [ ] A new landing page for the new cohort and related updates
  - [ ] Move the previous cohort page to the cohort list page
  - [ ] Add the data to the list on the landing page
- [ ] Action for this issue: @bebatut for other task lists

**Open Review**
- [ ] Place a request for the new page using the internal chair page
- [ ] Use the JSON content for the application form: https://github.com/open-life-science/application-forms/blob/master/openreview-application.json
- [ ] Use JSON content for review rubric: https://github.com/open-life-science/application-forms/blob/master/openreview-review-rubric.json
- [ ] Action for this issue: Malvika to create a screen grab video for how to set up the OpenReview platform

**Google Drive**
- [ ] Create a new folder for the new cohort
- [ ] Copy over all the placeholder files

**Civi system**
- [ ] Action for this issue: Emmy and Paz to update
